name: Build and Publish VM Image

on:
  push:
    branches:
      - main

env:
  HASHICORP_CLOUD_TOKEN: ${{ secrets.HASHICORP_CLOUD_TOKEN }}
  PROMETHEUS_BASIC_AUTH_PASS: ${{ secrets.PROMETHEUS_BASIC_AUTH_PASS }}

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          subfolder: [ prometheus, grafana ]
        fail-fast: true

    steps:
    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.0
      
    - name: Set up Ansible
      run: python3 -m pip install ansible
    
    - name: Build image
      run: | 
        cd $subfolder
        sh pre-build.sh
        packer build .
      
    # - name: Publish image
    #   run: packer push -name packer-$subfolder-$TIMESTAMP .
    