name: Build and Publish VM Image

on:
  push:
    branches:
      - main

env: 
  PROJECT_ID: aa-devops
  ZONE: us
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  PROMETHEUS_BASIC_AUTH_PASS: ${{ secrets.PROMETHEUS_BASIC_AUTH_PASS }}

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: andersondarioo/packer-ansible:1.0.0
    strategy:
        matrix:
          subfolder: [ prometheus, grafana ]
        fail-fast: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        
    - name: Build image
      run: | 
        cd ${{ matrix.subfolder }}
        packer build -var "project_id=$PROJECT_ID" -var "zone=$ZONE" .
      
    # - name: Publish image
    #   run: packer push -name packer-$subfolder-$TIMESTAMP .
    