name: Build and Publish VM Image

on:
  push:
    branches:
      - main

env:
  HASHICORP_CLOUD_TOKEN: ${{ secrets.HASHICORP_CLOUD_TOKEN }}
  PROMETHEUS_BASIC_AUTH_PASS: ${{ secrets.PROMETHEUS_BASIC_AUTH_PASS }}

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: andersondarioo/packer-ansible:1.0.0
    strategy:
        matrix:
          subfolder: [ prometheus, grafana ]
        fail-fast: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build image
      run: | 
        cd ${{ matrix.subfolder }}
        sh pre-build.sh
        packer build .
      
    # - name: Publish image
    #   run: packer push -name packer-$subfolder-$TIMESTAMP .
    